"""add courses and enrollments

Revision ID: 6b0e09b04dd6
Revises: dccbae55a502
Create Date: 2026-10-03 22:39:12.685511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b0e09b04dd6'
down_revision: Union[str, Sequence[str], None] = 'dccbae55a502'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('course_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_contents_course_id'), 'contents', ['course_id'], unique=False)
    op.create_foreign_key(None, 'contents', 'courses', ['course_id'], ['id'], ondelete='SET NULL')
    op.add_column('quizzes', sa.Column('course_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_quizzes_course_id'), 'quizzes', ['course_id'], unique=False)
    op.create_foreign_key(None, 'quizzes', 'courses', ['course_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quizzes', type_='foreignkey')
    op.drop_index(op.f('ix_quizzes_course_id'), table_name='quizzes')
    op.drop_column('quizzes', 'course_id')
    op.drop_constraint(None, 'contents', type_='foreignkey')
    op.drop_index(op.f('ix_contents_course_id'), table_name='contents')
    op.drop_column('contents', 'course_id')
    # ### end Alembic commands ###
